using System;

namespace Mtconnect.AdapterSdk.Contracts
{
    /// <summary>
    /// Indicators for what may contribute to timestamp drift
    /// </summary>
    [Flags]
    public enum TimestampDriftCauses
    {
        /// <summary>
        /// There are no drift causes or they are unknown.
        /// </summary>
        None = 0,
        /// <summary>
        /// Timestamp drift can occur when clocks on different systems are not perfectly synchronized. This can cause timestamps generated on one system to be slightly different from the actual time of the event.
        /// </summary>
        ClockDrift = 1 << 0,
        /// <summary>
        /// Timestamp drift can occur due to the time it takes to write data to disk, as the actual time of the event may be slightly different from the time recorded in the timestamp.
        /// </summary>
        DiskWrite = 1 << 1,
        /// <summary>
        /// Disk read time refers to the amount of time it takes to read data from disk. If a system is reading a timestamp from disk to determine the time of an event, the actual time of the event may be slightly different from the time recorded in the timestamp due to the disk read time. This can cause timestamp drift, as the actual time of the event and the time recorded in the timestamp may not be perfectly synchronized.
        /// </summary>
        DiskRead = 1 << 2,
        /// <summary>
        /// Timestamp drift can occur due to the time it takes for a system to handle an interrupt, which can cause inaccuracies in timestamps generated by the system.
        /// </summary>
        InterruptHandlingDelay = 1 << 3,
        /// <summary>
        /// Timestamp drift can occur due to the amount of time it takes for a network packet to travel from the source to the destination. This delay can cause the actual time of the event to be different from the time recorded in the timestamp.
        /// </summary>
        NetworkDelay = 1 << 4,
        /// <summary>
        /// Timestamp drift can occur due to small variations in the time it takes for a CPU to perform operations, which can cause inaccuracies in timestamps generated by the system.
        /// </summary>
        CpuJitter = 1 << 5,
    }
}
